### ISSUE TITLE
[BUG] Paths will multiple dashes are not supported

### ISSUE THREAD

**Issue by th-ko** [eddeee888/graphql-code-generator-plugins#192]
**Describe the bug**
Within the schema-folder I have a subfolder called "some-thing-else". In the 'resolvers.generated.ts' the import will look like this:
import { MutationRoot as some_thing-else_MutationRoot } from './some-thing-else/resolvers/MutationRoot.js'

**To Reproduce**
Run '@eddeee888/gcg-typescript-resolver-files' (with "mode: 'merged'")

**Expected behavior**
All dashes  in the alias get replaced by underscores

**Versions**

- OS: Windows
- OS Version: 11
- Package name and version:
    "@eddeee888/gcg-typescript-resolver-files": "^0.7.1",
    "@graphql-codegen/cli": "^5.0.0",

**Comment by eddeee888** [comment]
Thanks @th-ko ! I'll take a look at this soon

**Comment by eddeee888** [comment]
Hi @th-ko ,

This should be fixed in this PR: https://github.com/eddeee888/graphql-code-generator-plugins/pull/194/files

Please try this alpha release to see if it fixes your issue:

```
yarn add -D @eddeee888/gcg-typescript-resolver-files@pr196-run325-1
```

**Comment by eddeee888** [comment]
Closing this because the newer version should fix this. Please open another issue if the problem persists. Thank you!
