### ISSUE TITLE
how to programmatic usage ? 

### ISSUE THREAD

**Issue by productdevbook** [eddeee888/graphql-code-generator-plugins#214]
https://the-guild.dev/graphql/codegen/docs/advanced/programmatic-usage

I failed to add your plugin

**Comment by eddeee888** [comment]
Hello @productdevbook , could you please share what you have tried please? 🙂

**Comment by productdevbook** [comment]
Your structure does not support the structure in the link I posted. Can you create a plugin structure

**Comment by eddeee888** [comment]
Hello @productdevbook 👋 

Sorry, it took longer than I wish to get to your message.

It looks like the programmatic usage link you posted is mainly for a normal plugin. Here's _roughly_ what's needed to run codegen programmatically for a preset:

```js
// generate.mjs
import * as fs from 'fs/promises';
import * as path from 'path';
import * as url from 'url';
import { codegen } from '@graphql-codegen/core';
import { preset } from '@eddeee888/gcg-typescript-resolver-files';
import { loadFilesSync } from '@graphql-tools/load-files';
import { mergeTypeDefs } from '@graphql-tools/merge';
import { loadSchema } from '@graphql-tools/load';
import { GraphQLFileLoader } from '@graphql-tools/graphql-file-loader';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const typeDefs = mergeTypeDefs(loadFilesSync('libs/graph-backend/**/*.graphqls'));
const schemas = await loadSchema('libs/graph-backend/**/*.graphqls', {
  loaders: [new GraphQLFileLoader()],
  includeSources: true, // Note: This is important as the preset relies on sources to do smart stuff
});

const generateOptions = await preset.buildGeneratesSection({
  baseOutputDir: 'src/schema',
  presetConfig: {},
  schema: typeDefs,
  schemaAst: schemas,
  config: {},
  documents: [],
});

Promise.all(
  generateOptions.map(async (option) => {
    const output = await codegen(option);
    await fs.writeFile(path.join(__dirname, option.filename), output, 'utf8');
  })
);

```
Then, you can run the following to generate the files:

```
$ node generate.mjs
```

Note: As you can see from the above, we are loading `.graphql` files twice to generate `typeDefs` and `schemas`. I'm not sure what's the best way to load typeDefs and schemas once. Maybe something to check with the folks in GraphQL Discord?

**Comment by productdevbook** [comment]
Thank you working, but [example 2](https://github.com/productdevbook/programmatic-graphql) please folder check.

1. cd example2
2. pnpm install
4. cd templates/nuxt
5. tsx index.ts

Dont export `example2/src` It takes the name of the road.

![CleanShot 2024-02-02 at 08 48 39](https://github.com/eddeee888/graphql-code-generator-plugins/assets/38668796/47250240-bbf8-49d9-a815-b453d4d8056a)

**Comment by eddeee888** [comment]
I think your `baseOutputDir` has to be relative to your current folder. 

So, assuming your current working directory is `/Users/productdevbook/testalani/programatic-graphql`, then it'd be something like this: `example2/src`

**Comment by productdevbook** [comment]
but I need to be able to give it where I want, I'm building a dynamic structure. You need to send it accordingly.

I think you need to count something like `cwd` and let us change it.

**Comment by eddeee888** [comment]
Sorry for not getting to this earlier. I think that could be a good feature request in https://github.com/dotansimha/graphql-code-generator 🙂
Server Preset is basically a plugin for the generator and if it's actioned there, it'd work here too

**Comment by eddeee888** [comment]
Closing this as it looks solved upstream. Thank you!
