### ISSUE TITLE
[BUG] Not all `*.mappers.ts` files are detected

### ISSUE THREAD

**Issue by lensbart** [eddeee888/graphql-code-generator-plugins#217]
Hello,

First of all, thanks for developing the server preset. It allowed me to remove large chunks of boilerplate code.

Not entirely sure how to narrow down this bug, but I have the following setup:

```ts
// codegen config file
'apps/api/src/schema/': {
  ...defineConfig({
    emitLegacyCommonJSImports: false,
    resolverMainFile: './__generated__/resolvers.ts',
    resolverTypesPath: './__generated__/types.ts',
    tsConfigFilePath: './apps/api/tsconfig.json',
    typeDefsFilePath: './__generated__/typeDefs.ts',
    typesPluginsConfig: {
      contextType: 'src/index.js#Context',
    },
  }),
},
```

and a couple of modules: `annotation`, `base`, `block` and `inline`. If I have the following mapper files (all paths below are inside `src/schema`):
* `annotation/annotation.mappers.ts`
* `base/base.mappers.ts`
* `block/block.mappers.ts`
* `inline/inline.mappers.ts`

then only `annotation.mappers.ts` and `block.mappers.ts` get detected and imported into the generated `types.ts` file.

If I rename these files to:
* `annotation/annotation.mappers.ts`
* `base/schema.mappers.ts`
* `block/block.mappers.ts`
* `inline/inline.mappers.ts`

then all except for `inline.mappers.ts` are imported into `types.ts`

If I rename these files to:
* `annotation/schema.mappers.ts`
* `base/schema.mappers.ts`
* `block/schema.mappers.ts`
* `inline/schema.mappers.ts`

then only the second file gets imported into the generated `types.ts` file.

The only thing I changed to achieve these different results is the filename. Each of these files contain a single statement, in the form of 
```ts
// see https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset#adding-mappers
export type {
  Something as SomethingMapper,
  SomethingElse as SomethingElseMapper
} from 'src/__generated__/prisma/index.js'
```
None of these exports have overlapping names.

Hope this helps!

**Comment by eddeee888** [comment]
Hello @lensbart !

Thanks for using the preset, and apologies for the delayed response.

I've tried to re-create your setup using this [example Codesandbox](https://codesandbox.io/p/devbox/clever-hellman-y78xd5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clptkwroj00053b83vpgnv9q7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clptkwroj00023b83din5ohp5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clptkwroj00033b8365f5l5yi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clptkwroj00043b83fzjp9dzb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clptkwroj00023b83din5ohp5%2522%253A%257B%2522id%2522%253A%2522clptkwroj00023b83din5ohp5%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clptkwroj00043b83fzjp9dzb%2522%253A%257B%2522id%2522%253A%2522clptkwroj00043b83fzjp9dzb%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clptkwroj00033b8365f5l5yi%2522%253A%257B%2522id%2522%253A%2522clptkwroj00033b8365f5l5yi%2522%252C%2522activeTabId%2522%253A%2522clptlcrus014e3b83spv21g0e%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clptkywdc008l3b83wowq5qeh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clptlcrus014e3b83spv21g0e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clptlcutx002eeff48j3d6inh%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):
- have a `tsconfig.json` with alias path to `src/__generated__/prisma/index`
- Codegen setup:
```ts
"src/schema": defineConfig({
    emitLegacyCommonJSImports: false,
    resolverMainFile: "./__generated__/resolvers.ts",
    resolverTypesPath: "./__generated__/types.ts",
    typeDefsFilePath: "./__generated__/typeDefs.ts",
    tsConfigFilePath: "./tsconfig.json",
    typesPluginsConfig: {
      contextType: "../../index#ResolverContext",
    },
  }),
```
- Schema files and accompanying mappers:
  - `base/schema.graphql` and `base/schema.mappers.ts`
  - `annotations/annotations.graphql` and `annotations/annotations.mappers.ts`
  - `block/block.graphql` and `block/block.mappers.ts`
  - `inline/inline.graphql` and `inline/inline.mappers.ts`
- Each mapper files either exports type using relative path or alias path e.g:
  - `export type { Block as BlockMapper } from "src/__generated__/prisma/index";`
  - `export type { Inline as InlineMapper } from "../../__generated__/prisma/index";`

The generated type file is correctly importing the mapper interfaces:

![Screenshot 2023-12-06 at 9 14 03 pm](https://github.com/eddeee888/graphql-code-generator-plugins/assets/33769523/59110562-6647-4e0e-a314-0b1b411cbb06)

The only thing I haven't tried is setting up your config in a monorepo (which seems to be your real setup). However, I have an app that uses codegen in an Nx monorepo and it is working fine too.

Do you have an example where I could check out to debug? 🙂

**Comment by lensbart** [comment]
Sorry for the late response — I can’t easily provide an example, because the project I’m working on is closed source. Feel free to close this issue, I have resolved it on my end by putting all mappers in a single `schema.mappers.ts` file.

**Comment by eddeee888** [comment]
Thanks @lensbart !
