### ISSUE TITLE
[FEAT] Add LICENSE file 

### ISSUE THREAD

**Issue by dawningfuture** [eddeee888/graphql-code-generator-plugins#220]
**Is your feature request related to a problem? Please describe.**
This contribution to this ecosystem is fantastic! - but for me to be able to use it, the policies that be say that the repo has to include a LICENSE file. So that the lawyers upstairs can lawyer about something else, I'd like to request a LICENSE file feature for this repo.

**Describe the solution you'd like**
If you have a spare 45 seconds,

- [ ] Hit that `Add file` button on the repo page, make a `LICENSE` file, and drop the [MIT license text](https://opensource.org/license/mit/) in there 
- [ ] Merge that onto the default branch (master in this case)
- [ ] Momentarily marvel at the magic of code / build more awesome stuff like this (and this is definitely awesome 👏 )

** Above adapted from [GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Describe alternatives you've considered**
-  I wondered about the `"license": "MIT"` property in some of the `package.json`s, but [after consulting with my Internet](https://opensource.stackexchange.com/a/7244), it looks like that won't count
-  For better or worse, it turns out the obvious "fork-and-do-anything-else-with-it" strategy [wouldn't work either](https://opensource.stackexchange.com/a/1157). I guess [GitHub basically only covers](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users) clicking the Fork button and admiring (but not using, modifying, distributing, etc...) your work from its new home in GitHub

**Additional context**
I just spent way too long reading about copyright, licensing, free software, free (libre) software - so I guess..?

DISCLAIMER: [This is not legal advice](https://notlegaladvice.law/). I'm definitely not a lawyer, I just drank too much coffee and have an Internet connection.

Thanks for this repo, I'm excited to use it 👍

**Comment by eddeee888** [comment]
Thanks for the suggestion @dawningfuture 🙏 ! 

It's now done in https://github.com/eddeee888/graphql-code-generator-plugins/pull/221
