### ISSUE TITLE
[FEAT]Mapper supports interface extends

### ISSUE THREAD

**Issue by kgtkr** [eddeee888/graphql-code-generator-plugins#223]
**Is your feature request related to a problem? Please describe.**
Currently mapper does not recognize extended fields in interface

```graphql
# schema.graphql
type Test {
  id: ID!
  name: String!
  description: String!
}
```

```ts
// schema.mappers.ts
interface Base {
  description: string;
}

export interface TestMapper extends Base {
  id: string;
  name: string;
}
```

```ts
// Test.ts
import type   { TestResolvers } from './../../types.generated';
    export const Test: TestResolvers = {
    /* Implement Test resolver logic here */
        description: () => { /* Test.description resolver is required because Test.description exists but TestMapper.description does not */ }
    };
```

**Describe the solution you'd like**
Support interface extends.

**Describe alternatives you've considered**
Use class extends instead of interface.

```ts
class Base {
  description!: string;
}

export class TestMapper extends Base {
  id!: string;
  name!: string;
}

```

**Additional context**

**Comment by eddeee888** [comment]
Hi @kgtkr !

Thanks for reporting this issue. Here's the PR for the fix: https://github.com/eddeee888/graphql-code-generator-plugins/pull/242

Could you try the alpha version to see if it fixes your issue, please? 🙏

```shell
yarn add -ED @eddeee888/gcg-typescript-resolver-files@pr242-run423-1
```

**Comment by kgtkr** [comment]
@eddeee888 thanks for the great patch
I can confirm that the issue is fixed in my project

**Comment by eddeee888** [comment]
This is now available in https://github.com/eddeee888/graphql-code-generator-plugins/releases/tag/%40eddeee888%2Fgcg-typescript-resolver-files%400.7.4. Thank you!
