### ISSUE TITLE
[DX] Resolvers chains working by default

### ISSUE THREAD

**Issue by konhi** [eddeee888/graphql-code-generator-plugins#225]
**Is your feature request related to a problem? Please describe.**
The way this plugin generates codes naturally makes users do resolvers chaining. This is a standard GraphQL practice documented by [Apollo Docs > Server > Resolvers > Resolver Chains](https://www.apollographql.com/docs/apollo-server/data/resolvers#resolver-chains). 

When using this plugin for the first time, it was unexpected to me that this wasn't supported by default. I spent few hours trying to look for a solution.

**Describe the solution you'd like**
Enable support for resolver chaining by making this config default. We can also just update readme of this plugin and this guide: https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset

```ts
const config: CodegenConfig = {
  schema: '**/schema.graphql',
  generates: {
    'src/schema': defineConfig({
      typesPluginsConfig: {
        /* This is required for resolvers chaining */
        useIndexSignature: true,
        defaultMapper: 'Partial<{T}>',
      }
    })
  }
}
```

**Additional context**
- https://github.com/dotansimha/graphql-code-generator/issues/3828 
- https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#integration-with-apollo-server

**Comment by arjunyel** [comment]
if you are using resolver chains then you will need nested partials using [`utility-types`](https://github.com/piotrwitek/utility-types) https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#allow-deep-partial-with-utility-types

```typescript
const config: CodegenConfig = {
 schema: "**/schema.graphql",
 generates: {
  "src/schema": defineConfig({
   add: {
    "./types.generated.ts": {
     content: "import type { DeepPartial } from 'utility-types';",
    },
   },
   typesPluginsConfig: {
    defaultMapper: "DeepPartial<{T}>",
   },
  }),
 },
};
```

**Comment by eddeee888** [comment]
Hello 👋  Thanks for creating this issue. I think there's definitely something we can work out to make the usage clearer. 🙂

For context, this plugin is created to have first-class support the [mappers](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#mappers) way enabling resolver chaining for the following benefits:

**1. Predictability and runtime safety when using a mapper - or not**

By default, codegen matches resolver's TS types with GraphQL field output type. This eliminates the chance where someone forgets to return null into a non-nullable GraphQL field - which is possible with `Partial` or `DeepPartial` - and cause a runtime error. On the other hand: 
- By using `mappers`, we explicitly tell codegen which value we don't want to return in a resolver, shifting the responsibilities to the following resolvers.
- And by using this plugin, it automatically creates chaining resolvers at the leaf node if there could be runtime error e.g. nullable value being returned into a non-nullable GraphQL field, mismatched types, etc.

**2. Consistent baseline object when multiple resolvers return the same type**

Consider the following schema:

```graphql
type Cat {
  owner: Person!
}

type Dog {
  owner: Person!
}

type Person {
  id: ID!
  name: String!
}
```

With `Partial` or `DeepPartial`, it's easy to accidentally return the inconsistent `Person` object in `Cat.owner` and `Dog.owner` resolvers, making it much easier to hit runtime errors, especially in bigger apps e.g.

```ts
const resolvers: Resolvers = {
  Cat: {
    owner: () => ({ id: "100" }) // 👈 object with only `id` can be return here, because `Person` is partial. This will result in runtime error.
  }
  Dog: {
    owner: () => ({ name: "Bart" }) // 👈 object with only `name` can be return here, because `Person` is partial. This will result in runtime error.
  }
}
```

On the other hand, `Person` resolvers wouldn't know what's being passed in, making it hard to code and may cause runtime errors:

```ts
const resolvers: Resolvers = {
  // Same Cat/Dog resolvers as before
  Person: {
    id: ({ id }) => id // 👈 This will trigger type error because `id` is nullable from using `Partial`
    // 👈 No `name` resolver... which means it'd error if clients query for `Cat.owner` because `Person.name` is non-nullable in the Graph, but we don't handle the nullable case
  }
}

```

---

For these reasons, `Partial` and `DeepPartial` mappers is supported via your mentioned config options, but not by default for this plugin. I'll add some notes to the guides to clarify the reasoning 🙂

---

For context, here's the file convention of using `mappers` when using this plugin: https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset#adding-mappers

**Comment by eddeee888** [comment]
Hi @arjunyel , sure!

I've set up a small GraphQL server with some mocked data here: https://github.com/eddeee888/graphql-server-template

Let's look at the related part of the schema extracted from that repo:

```graphql
# book/schema.graphql
type Book {
  id: ID!
  isbn: String!
}

# user/schema.graphql
extend type Query {
  user(id: ID!): User
}
type User {
  id: ID!
  fullName: String!
  booksRead: [Book!]!
}
```

In `Query.user` resolver, we don't want to implement with `booksRead` as we want to let `User.booksRead` handle that logic.

---

Here's how we can do with this preset:

1. Declare a User mapper in [user/schema.mapper.ts](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/user/schema.mappers.ts). This mapper is the minimal shape that can be used to resolve any User fields:

```ts
// user/schema.mappers.ts

// Preset detects a mapper by the type name `User` (GraphQL type) + `Mapper` (The customisable suffix)
export type UserMapper = { 
  id: string;
  firstName: string;
  lastName: string;
};
```

What this means is we can now pass this mapper object into any resolver that is supposed to return a GraphQL `User` node. Our [Query.user](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/user/resolvers/Query/user.ts) may look something like this:

```ts
// user/resolvers/Query/user.ts
export const user: NonNullable<QueryResolvers["user"]> = async (
  _parent,
  { id },
  { data },
) => {
  // We must now return a consistent `UserMapper` into GraphQL `User` node
  // Without the UserMapper, we must return `{ id: string, fullName: string, booksRead: Book[] }`
  return {
    id: "1",
    firstName: "Bart",
    lastName: "Simpson"
  }
};
```

And we can resolve [User.booksRead](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/user/resolvers/User.ts) like this:

```ts
// user/resolvers/User.ts 
export const User: UserResolvers = {
  booksRead: (parent, __, { data }) => { // `parent` is `UserMapper`
    /* Do booksRead resolver logic here*/
  },
  fullName: (parent) => {
    //👇 Server preset would generate `User.fullName` resolver and tell us _why_ we this is generated
    /* User.fullName resolver is required because User.fullName exists but UserMapper.fullName does not */
    return `${parent.firstName} ${parent.lastName}`;
  },
};
```

---

You can find the full example in the mentioned [repo](https://github.com/eddeee888/graphql-server-template) with these main files:
- [book schema](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/book/schema.graphql)
- [user schema](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/user/schema.graphql)
- [user mapper](https://github.com/eddeee888/graphql-server-template/blob/ca7438f30a70793a91933e105d42d27405e802e2/src/schema/user/schema.mappers.ts#L1-L5)
- [Query.user returning a user mapper](https://github.com/eddeee888/graphql-server-template/blob/ca7438f30a70793a91933e105d42d27405e802e2/src/schema/user/resolvers/Query/user.ts#L7-L8)
- [User resolver chaining](https://github.com/eddeee888/graphql-server-template/blob/master/src/schema/user/resolvers/User.ts)

**Comment by eddeee888** [comment]
Let me know if this doesn't answer your question @arjunyel ! Happy to chat more.
If we are happy with this discussion, I'll close this issue in 3 days and update the docs

**Comment by arjunyel** [comment]
@eddeee888 makes total sense, you are the biggest legend in history!
