### ISSUE TITLE
[FEAT] Config option to allow for nested modules

### ISSUE THREAD

**Issue by jb-1980** [eddeee888/graphql-code-generator-plugins#243]
**Is your feature request related to a problem? Please describe.**
I have to keep a very flat file structure to use this. I would like to be able to organize modules together in subdomains to facilitate domain driven design, i.e.:
```
src/schema
├── school
│   └── demographics
│   │   ├── resolvers
│   │   ├── schema.graphql
├── students
│   ├── profile
│   ├── avatar
│   │   ├── resolvers
│   │   ├── schema.graphql
│   └── guardians
├── teachers
│   ├── profile
│   ├── avatar
│   │   ├── resolvers
│   │   └── schema.graphql

```
If I have a `codegen.ts` like

```ts
// codegen.ts
import type { CodegenConfig } from '@graphql-codegen/cli';
import { defineConfig } from '@eddeee888/gcg-typescript-resolver-files';

const config: CodegenConfig = {
  schema: '**/schema.graphql',
  generates: {
    'src/schema': defineConfig(),
  },
};

export default config;
```

Then it will generate a file structure like
```
src/schema
├── demographics
│   └── resolvers
├── profile
│   └── resolvers
├── avatar
│   └── resolvers
...
```
The issue with that is that the resolvers are ambiguous. They may go with the `students` or with the `teachers`. Like, It seems like it is some race condition as to which resolvers are going to get into `avatar/resolvers`. Moreover, the code is no longer collocated within its subdomain.

**Describe the solution you'd like**
I would like an option similar to that offered by the [near-operation-file-preset](https://the-guild.dev/graphql/codegen/plugins/presets/near-operation-file-preset) plugin. Namely, that setting the option to `true` would place all resolver files inside the directory where `schema.graphql` is located instead of `<baseOutputDir>/<moduleName>/<resolverRelativeTargetDir>`.

Output should be `<baseOutputDir>/**/<moduleInSubdomain>/<resolverRelativeTargetDir>`

**Describe alternatives you've considered**
* I have tried different variants of the `resolverRelativeTargetDir`, but they always are give a similar result.
* I could have various paths in the `generates` object in `codegen.ts`, but then that takes up [Maintainers](https://the-guild.dev/graphql/codegen/plugins/presets/near-operation-file-preset) time.
* We just get everyone to agree on a flat file structure and make sure to namespace things. Which you kind of have to do anyway because teachers avatars and student avatars can't have the same schema `type Avatar`.

**Comment by eddeee888** [comment]
This is now available in [v0.7.4](https://github.com/eddeee888/graphql-code-generator-plugins/releases/tag/%40eddeee888%2Fgcg-typescript-resolver-files%400.7.4). Thank you!
