### ISSUE TITLE
[FEAT] Pretty print typeDefs to reduce merge conflicts in VCS

### ISSUE THREAD

**Issue by kdawgwilk** [eddeee888/graphql-code-generator-plugins#268]
**Is your feature request related to a problem? Please describe.**
Because the `typeDefs.generated.ts` file is a single line it always ends up causing merge conflicts when checked in.  

**Describe the solution you'd like**
I would like the JSON object to be pretty printed on multiple lines so that its less likely to cause merge conflicts

**Describe alternatives you've considered**
Not checking in generated code.  There are tradeoffs but I think those trade offs are another discussion and this would be useful either way.

**Additional context**
N/A

**Comment by eddeee888** [comment]
Hi @kdawgwilk 👋 

I think this is a perfect use case for [Codegen's life cycle hooks](https://the-guild.dev/graphql/codegen/docs/config-reference/lifecycle-hooks)

A setting I normally use is to run `prettier` on generated files using `afterAllFileWrite: ["prettier --write"]`.

Here's an example config:

```ts
import type { CodegenConfig } from "@graphql-codegen/cli";
import { defineConfig } from "@eddeee888/gcg-typescript-resolver-files";

const config: CodegenConfig = {
  schema: "**/schema.graphql",
  hooks: {
    afterAllFileWrite: ["prettier --write"], // This can be added to run prettier on all generated files
  },
  generates: {
    "src/schema": defineConfig(),
  },
};
export default config;
```

Here's an example prettified output: https://github.com/eddeee888/graphql-code-generator-plugins/blob/master/packages/typescript-resolver-files-e2e/src/test-modules/modules/typeDefs.generated.ts

**Comment by eddeee888** [comment]
I see. Could you help me understand if this is happening because multiple devs are making schema changes at the same time, causing conflicts?

If you are finding it getting in the way, maybe you can add it to `.gitignore`?

**Comment by eddeee888** [comment]
FYI in [v0.10.1](https://github.com/eddeee888/graphql-code-generator-plugins/releases/tag/%40eddeee888%2Fgcg-typescript-resolver-files%400.10.1), there's an update to remove `loc`.

I'll close this for now but if there's still issues, let me know 🙂
