### ISSUE TITLE
How to override the ID scalar?

### ISSUE THREAD

**Issue by Colt45s** [eddeee888/graphql-code-generator-plugins#333]
I am trying to implement an ID scalar according to the GraphQL Global Object Identification Specification.

codegen.ts

```ts
import { defineConfig } from "@eddeee888/gcg-typescript-resolver-files";
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "internal/schema/**/*.graphql",
  generates: {
    "internal/schema": defineConfig({
      scalarsOverrides: {
        ID: {
          resolver: "base/resolvers/ID#IDResolver",
        },
      },
    }),
  },
};

export default config;
```

base/resolvers/ID.ts

```ts
export const IDResolver = {};
```

No resolver is generated in resolvers.generated.ts.

**Comment by eddeee888** [comment]
Hi @Colt45s ,

It looks like you can't override default scalars like `ID` at runtime: https://github.com/graphql/graphql-js/issues/917
Since it cannot be done at that level, I don't think we can support it at codegen level 🙂

Unless you are able to override the default scalar somehow?

**Comment by eddeee888** [comment]
Closing this as overriding default scalar is not currently supported at GraphQL level. Thanks for reaching out!
