### ISSUE TITLE
Config option for using esm style .js imports

### ISSUE THREAD

**Issue by JustusFluegel** [eddeee888/graphql-code-generator-plugins#65]
Currently the generated code generates imports that do not end with ".js". This prevents the usage of generated code in esm modules, as those imports are required to end in ".js". It would be great if there was a config option to enable this.

**Comment by JustusFluegel** [comment]
I don't quite know to add config options so if you could give me some points that i would have to do that would be helpful and I would be able to create a pr.

**Comment by eddeee888** [comment]
Hello @JustusFluegel ! Thanks for looking into this 🙌 

Here's the process of adding a new config option:

- Add the option into [RawPresetConfig](https://github.com/eddeee888/graphql-code-generator-plugins/blob/6e243541b5356627456651642f9e9df25fbb0eff/packages/typescript-resolver-files/src/validatePresetConfig/validatePresetConfig.ts#L38-L51). This is what the preset receives from codegen config file. We'll most likely get optional values here.
- Add the parsed option into [ParsedPresetConfig](https://github.com/eddeee888/graphql-code-generator-plugins/blob/6e243541b5356627456651642f9e9df25fbb0eff/packages/typescript-resolver-files/src/validatePresetConfig/validatePresetConfig.ts#L24-L36). This is what the version we use for implementation. This has narrower types than `RawPresetConfig` and no options should be `undefined` here.
- Grab parsed config option inside the [preset](https://github.com/eddeee888/graphql-code-generator-plugins/blob/33e9c6f6dfaae18f3a2a761b6ee6f65edc38a778/packages/typescript-resolver-files/src/preset.ts#L33-L45)
- Then you can start using the config to implement the logic
- Documentation of config options can be added in the [package README's config section](https://github.com/eddeee888/graphql-code-generator-plugins/blob/master/packages/typescript-resolver-files/README.md#config)

---

Looks like Codegen has a similar option called `emitLegacyCommonJSImports` for `typescript` and `typescript-resolvers` plugins. [Documentation here](https://the-guild.dev/graphql/codegen/docs/getting-started/esm-typescript-usage#codegen-configuration). Would be good to have the same name! :)
