### ISSUE TITLE
Missing support for typesPluginsConfig.typesPrefix

### ISSUE THREAD

**Issue by polRk** [eddeee888/graphql-code-generator-plugins#77]
https://github.com/eddeee888/graphql-code-generator-plugins/blob/392fd0fe6fb157305f74df8f29e95256b12c506e/packages/typescript-resolver-files/src/generateResolverFiles/addResolverMainFile.ts#L134

**Comment by eddeee888** [comment]
This is supported in v0.11. Please let me know if it still doesn't work and I'll re-open this issue 🙂
