### ISSUE TITLE
feat: add support for custom add

### ISSUE THREAD

**Issue by polRk** [eddeee888/graphql-code-generator-plugins#79]

**Comment by eddeee888** [comment]
Hi @polRk , can you elaborate more on this feature please? 🙂

- What problem does this solve?
- How does it work?
- Why do we need this in the preset?
- Any other solutions if you've tried?

**Comment by eddeee888** [comment]
There's now experimental support for the generated type file in v0.7.0: https://github.com/eddeee888/graphql-code-generator-plugins/releases/tag/%40eddeee888%2Fgcg-typescript-resolver-files%400.7.0

If you need more support, feel free to open another issue. Thanks!
