### ISSUE TITLE
[BUG] Federation support.

### ISSUE THREAD

**Issue by patrickdronk** [eddeee888/graphql-code-generator-plugins#90]
I'm unsure if this is a bug, or just not in the preset. But currently, I'm trying to use the preset in combination with federation. 
But I'm not seeing any types being generated. 

**To Reproduce**
Use the following config:
```
import type { CodegenConfig } from '@graphql-codegen/cli'
import { preset } from '@eddeee888/gcg-typescript-resolver-files'

const config: CodegenConfig = {
  schema: '**/schema.graphql',
  generates: {
    'src/schema': {
      preset,
      config: { federation: true },
    }
  }
}
export default config
```

generate types

**Expected behavior**
I expect a referenceResolver type to be generated.

**Comment by eddeee888** [comment]
Hello 👋 

You can pass `typescript-resolvers` config through `presetConfig.typesPluginsConfig` option. I'll update the README to make it clearer

In your case, this should work:

```ts
import type { CodegenConfig } from "@graphql-codegen/cli";
import { preset } from "@eddeee888/gcg-typescript-resolver-files";

const config: CodegenConfig = {
  schema: "**/schema.graphql",
  generates: {
    "src/schema": {
      preset,
      presetConfig: {
        typesPluginsConfig: {
          federation: true,
        },
      },
    },
  },
};
export default config;
```

Doing this adds a `_FieldSet` in `Scalars`:

![Screen Shot 2023-02-28 at 8 26 33 pm](https://user-images.githubusercontent.com/33769523/221810291-e823eddd-54af-4b9b-90f1-82dffafca092.png)

I also haven't tried federation so please let me know what else's missing. Thanks! 🙏
